require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/upload_category_links", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # UploadCategoryLink. As you add validations to UploadCategoryLink, be sure to
  # adjust the attributes here as well.
  before :each do 
    sign_in user = build(:user)
  end
  describe "DELETE /destroy" do
    it "destroys the requested upload_category_link" do
      upload_category_link = UploadCategoryLink.create!
      expect {
        delete upload_category_link_url(upload_category_link)
      }.to change(UploadCategoryLink, :count).by(-1)
    end

    it "redirects to the upload_category_links list" do
      upload_category_link = UploadCategoryLink.create!
      delete edit_upload_path(upload_category_link)
      expect(response).to redirect_to(upload_category_links_url)
    end
  end
end