development:
  secret_key_base: f08aef5a054f9d0c80a8f65685b848978db0842a313efb92c146c1293fd1dab9dfdc84d8c47d18856a67efacfec497375a9ef8c79858f7603e6506d7e4a663a2

test:
  secret_key_base: db9c28bff51cfe0cf54aaf5bd11af9a5d3b79e71d0f146c9b5c7febd6a7a5215172a57d7b27dd35a9e42cec454f183713ac4aa965ca614ba0a775d963575380e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") {nil} %>
  gcp:
    db_password: <%= ENV.fetch("PG_USER_KEY") {nil} %>
  beta_settings:
    cloud_sql_instances: amadeus-2000:asia-southeast1:amadeus-pg
